import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/myUi/AppSidebar";
import Component from "@/components/myUi/navBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GPTUI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>

      <body>
        <SidebarProvider>
          <AppSidebar />
          <main className=" relative w-full h-screen ">
            <SidebarTrigger />
            <Component />
            <div>{children}</div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
